### ISSUE TITLE
Encoder memory efficiency

### ISSUE THREAD

**Issue by stdex** [clue/reactphp-ndjson#20]
Hello.

I try to stream ndjson to file.
And it get me 128MB memory utilization (memory_get_peak_usage(true)).
This is too much for me (since the data size will be even larger than in my benchmark).

As I can see this is due to the fact that you are using buffer string in WritableResourceStream::$data
Should I make own implementation of WritableStreamInterface for workaround this problem?

```php
function encoderFileStreamTest()
{
    $tmpName = uniqid('tmp_', false);

    $filePath = __DIR__ . '/' . $tmpName . '.json';

    $loop = Factory::create();

    $stream = fopen('file://' . $filePath, 'wb+');

    $out = new WritableResourceStream($stream, $loop);
    $encoder = new Encoder($out);

    $max = 1000000;

    for ($i = 0; $i < $max; $i++) {

        $t = [
            '1' => 'cell1--' . $i,
            '2' => 'cell2--' . $i,
            '3' => 'cell3--' . $i,
            '4' => 'cell4--' . $i,
            '5' => 'cell5--' . $i,
        ];

        $encoder->write($t);
    }

    $loop->run();

    $encoder->end();
    $encoder->close();
}

$start = microtime(true);
encoderFileStreamTest();
$finish = microtime(true);
$delta = number_format($finish - $start, 1);
echo 'Output' . ' :: '  . $delta . ' sec., mem_peak: ' .  round(memory_get_peak_usage(true) / 1024 / 1024, 2);
```

**Comment by clue** [comment]
@stdex This is an interesting one, thanks for reporting!

The `Encoder` uses an underlying `WritableResourceStream` which are both in fact asynchronous and as such depend on the `LoopInterface` to flush this data to the output stream. This implies that data has to be buffered until the loop fires an event to flush the data to disk. This is all handled internally by the `write()` method. If its internal buffer is "full", it returns `false` as per https://github.com/reactphp/stream#write.

For your example, this means that you should stop writing more data to the encoder once `write()` returns `false`. You can then wait for the `drain` event to resume writing.

You can also turn your loop into a source stream implementing ReactPHP's `ReadableStreamInterface` and then `pipe()` the data to your target stream. Take a look at https://github.com/reactphp/http/blob/master/examples/92-client-benchmark-upload.php.

If you're following this logic, you can send bazillion of rows without seeing any memory spikes.

I hope this helps :+1:
